
package modelo.interfaces;
import modelo.entidades.*;
import modelo.gestion.*;
import modelo.interfaces.FrmPrincipal;


public class FrmGestionActas extends javax.swing.JFrame {
    private GestionActaElectoral gestionActas = new GestionActaElectoral();
    private GestionMesaElectoral gestionMesas = new GestionMesaElectoral();
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionActas.class.getName());

    /**
     * Creates new form FrmActas
     */
    public FrmGestionActas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoActa = new javax.swing.JTextField();
        txtCodigoMesaActa = new javax.swing.JTextField();
        txtTotalEmitidos = new javax.swing.JTextField();
        txtValidos = new javax.swing.JTextField();
        txtBlancos = new javax.swing.JTextField();
        txtNulos = new javax.swing.JTextField();
        btnRegistrarActa = new javax.swing.JButton();
        btnValidarActa = new javax.swing.JButton();
        btnVerActas = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo de acta:");

        jLabel2.setText("Codigo de mesa:");

        jLabel3.setText("Total votos emitidos:");

        jLabel4.setText("Votos validos:");

        jLabel5.setText("Votos nulos:");

        jLabel6.setText("Votos en blanco:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Gestion de Actas");

        txtCodigoActa.addActionListener(this::txtCodigoActaActionPerformed);

        btnRegistrarActa.setText("Registrar acta");
        btnRegistrarActa.addActionListener(this::btnRegistrarActaActionPerformed);

        btnValidarActa.setText("Validar acta");
        btnValidarActa.addActionListener(this::btnValidarActaActionPerformed);

        btnVerActas.setText("Ver actas");
        btnVerActas.addActionListener(this::btnVerActasActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(btnValidarActa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(btnVolver)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btnVerActas)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarActa)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigoMesaActa, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(txtTotalEmitidos)
                                    .addComponent(txtBlancos)
                                    .addComponent(txtValidos)
                                    .addComponent(txtNulos)
                                    .addComponent(txtCodigoActa))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoMesaActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalEmitidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarActa)
                    .addComponent(btnValidarActa)
                    .addComponent(btnVerActas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmPrincipal f = new FrmPrincipal();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActaActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoActa.getText();
        String codigoMesa = txtCodigoMesaActa.getText();

        int emitidos = Integer.parseInt(txtTotalEmitidos.getText());
        int validos = Integer.parseInt(txtValidos.getText());
        int blancos = Integer.parseInt(txtBlancos.getText());
        int nulos = Integer.parseInt(txtNulos.getText());

        MesaElectoral mesa = gestionMesas.buscarMesa(codigoMesa);

        if (mesa == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mesa no encontrada.");
            return;
        }

        ActaElectoral acta = new ActaElectoral(
                codigo, mesa, emitidos, validos, blancos, nulos
        );

        boolean registrada = gestionActas.registrarActa(acta);

        if (registrada) {
            javax.swing.JOptionPane.showMessageDialog(this, "Acta registrada.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Código repetido.");
        }   
    }//GEN-LAST:event_btnRegistrarActaActionPerformed

    private void btnValidarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActaActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoActa.getText();

    ActaElectoral acta = gestionActas.buscarActa(codigo);

        if (acta != null) {
            boolean valida = acta.validarActa();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "¿Acta válida? " + valida);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Acta no encontrada.");
    }
        
    }//GEN-LAST:event_btnValidarActaActionPerformed

    private void txtCodigoActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActaActionPerformed

    private void btnVerActasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActasActionPerformed
        // TODO add your handling code here:
        String lista = gestionActas.listarActas();
        javax.swing.JOptionPane.showMessageDialog(this, lista);
    }//GEN-LAST:event_btnVerActasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionActas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarActa;
    private javax.swing.JButton btnValidarActa;
    private javax.swing.JButton btnVerActas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBlancos;
    private javax.swing.JTextField txtCodigoActa;
    private javax.swing.JTextField txtCodigoMesaActa;
    private javax.swing.JTextField txtNulos;
    private javax.swing.JTextField txtTotalEmitidos;
    private javax.swing.JTextField txtValidos;
    // End of variables declaration//GEN-END:variables
}
