
package modelo.interfaces;
import modelo.gestion.GestionCandidato;
import modelo.gestion.GestionPartido;
import modelo.entidades.PartidoPolitico;
import modelo.entidades.Candidato;
import modelo.interfaces.FrmPrincipal;



public class FrmGestionCandidatos extends javax.swing.JFrame {
    private GestionCandidato gestion = new GestionCandidato();
    private GestionPartido gestionPartido = new GestionPartido();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionCandidatos.class.getName());

    /**
     * Creates new form FrmGestionCandidatos
     */
    public FrmGestionCandidatos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDniCandidato = new javax.swing.JTextField();
        txtNombreCandidato = new javax.swing.JTextField();
        txtApellidoCandidato = new javax.swing.JTextField();
        txtCodigoCandidato = new javax.swing.JTextField();
        txtVotosEmitidos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVotosPreferenciales = new javax.swing.JTextField();
        txtCodigoPartido = new javax.swing.JTextField();
        btnRegistrarCandidato = new javax.swing.JButton();
        btnModificarCandidato = new javax.swing.JButton();
        btnEliminarCandidato = new javax.swing.JButton();
        btnVerListaCandidato = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDniCandidato.addActionListener(this::txtDniCandidatoActionPerformed);

        jLabel1.setText("Dni de candidato");

        jLabel2.setText("Nombre de candidato");

        jLabel3.setText("Apellido del candidato");

        jLabel4.setText("Codigo del candidato");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Gestion de Candidatos");

        jLabel6.setText("Total de Votos Emitidos");

        jLabel7.setText("Total Votos Preferenciales");

        jLabel8.setText("Codigo del Partido");

        btnRegistrarCandidato.setText("Registrar");
        btnRegistrarCandidato.addActionListener(this::btnRegistrarCandidatoActionPerformed);

        btnModificarCandidato.setText("Modificar");
        btnModificarCandidato.addActionListener(this::btnModificarCandidatoActionPerformed);

        btnEliminarCandidato.setText("Eliminar");
        btnEliminarCandidato.addActionListener(this::btnEliminarCandidatoActionPerformed);

        btnVerListaCandidato.setText("Ver lista");
        btnVerListaCandidato.addActionListener(this::btnVerListaCandidatoActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtDniCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtNombreCandidato)
                            .addComponent(txtApellidoCandidato)
                            .addComponent(txtCodigoCandidato)
                            .addComponent(txtVotosEmitidos)
                            .addComponent(txtVotosPreferenciales)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarCandidato)
                        .addGap(59, 59, 59)
                        .addComponent(btnModificarCandidato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnEliminarCandidato)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnVerListaCandidato)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVotosEmitidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVotosPreferenciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCandidato)
                    .addComponent(btnModificarCandidato)
                    .addComponent(btnEliminarCandidato)
                    .addComponent(btnVerListaCandidato))
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniCandidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniCandidatoActionPerformed

    private void btnRegistrarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCandidatoActionPerformed
        // TODO add your handling code here:
        int dni = Integer.parseInt(txtDniCandidato.getText());
    String nombre = txtNombreCandidato.getText();
    String apellido = txtApellidoCandidato.getText();
    String codigo = txtCodigoCandidato.getText();
    int votosEmitidos = Integer.parseInt(txtVotosEmitidos.getText());
    int votosPreferenciales = Integer.parseInt(txtVotosPreferenciales.getText());
    String codigoPartido = txtCodigoPartido.getText();

    PartidoPolitico partido = gestionPartido.buscarPartido(codigoPartido);

    if (partido == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No existe el partido.");
        return;
    }

    Candidato c = new Candidato(
            dni,
            nombre,
            apellido,
            codigo,
            votosEmitidos,
            votosPreferenciales,
            partido
    );

    boolean registrado = gestion.registrarCandidato(c);

    if (registrado) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Candidato registrado correctamente.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Codigo repetido.");
    }
    }//GEN-LAST:event_btnRegistrarCandidatoActionPerformed

    private void btnModificarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCandidatoActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoCandidato.getText();
    String nombre = txtNombreCandidato.getText();
    String apellido = txtApellidoCandidato.getText();
    String codigoPartido = txtCodigoPartido.getText();

    PartidoPolitico partido = gestionPartido.buscarPartido(codigoPartido);

    if (partido == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No existe el partido.");
        return;
    }

    boolean modificado = gestion.modificarCandidato(
            codigo,
            nombre,
            apellido,
            partido
    );

    if (modificado) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Candidato modificado.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró el candidato.");
    }
    }//GEN-LAST:event_btnModificarCandidatoActionPerformed

    private void btnEliminarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCandidatoActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoCandidato.getText();

    boolean eliminado = gestion.eliminarCandidato(codigo);

    if (eliminado) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Candidato eliminado.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró el candidato.");
    }
    }//GEN-LAST:event_btnEliminarCandidatoActionPerformed

    private void btnVerListaCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListaCandidatoActionPerformed
        // TODO add your handling code here:
        String lista = gestion.listarCandidatos();

        javax.swing.JOptionPane.showMessageDialog(this, lista);
    }//GEN-LAST:event_btnVerListaCandidatoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmPrincipal f = new FrmPrincipal();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionCandidatos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCandidato;
    private javax.swing.JButton btnModificarCandidato;
    private javax.swing.JButton btnRegistrarCandidato;
    private javax.swing.JButton btnVerListaCandidato;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellidoCandidato;
    private javax.swing.JTextField txtCodigoCandidato;
    private javax.swing.JTextField txtCodigoPartido;
    private javax.swing.JTextField txtDniCandidato;
    private javax.swing.JTextField txtNombreCandidato;
    private javax.swing.JTextField txtVotosEmitidos;
    private javax.swing.JTextField txtVotosPreferenciales;
    // End of variables declaration//GEN-END:variables
}
