/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo.interfaces;
import modelo.interfaces.FrmPrincipal;
import modelo.gestion.*;


/**
 *
 * @author luigg
 */
public class FrmInforme extends javax.swing.JFrame {
    private GestionPartido gestionPartido = new GestionPartido();
    private GestionCandidato gestionCandidato = new GestionCandidato();
    private GestionMesaElectoral gestionMesas = new GestionMesaElectoral();
    private GestionActaElectoral gestionActas = new GestionActaElectoral();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInforme.class.getName());

    /**
     * Creates new form FrmInforme
     */
    public FrmInforme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloInforme = new javax.swing.JLabel();
        btnGenerarInforme = new javax.swing.JButton();
        tbnLimpiarInforme = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaInforme = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloInforme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloInforme.setText("Informe de Resultados Electorales");

        btnGenerarInforme.setText("Generar Informe");
        btnGenerarInforme.addActionListener(this::btnGenerarInformeActionPerformed);

        tbnLimpiarInforme.setText("Limpiar Informe");
        tbnLimpiarInforme.addActionListener(this::tbnLimpiarInformeActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        txtAreaInforme.setEditable(false);
        txtAreaInforme.setColumns(20);
        txtAreaInforme.setRows(5);
        jScrollPane1.setViewportView(txtAreaInforme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerarInforme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbnLimpiarInforme)
                                .addGap(10, 10, 10))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblTituloInforme)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTituloInforme)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarInforme)
                    .addComponent(tbnLimpiarInforme))
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmPrincipal f = new FrmPrincipal();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tbnLimpiarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnLimpiarInformeActionPerformed
        // TODO add your handling code here:
        txtAreaInforme.setText("");
       
    }//GEN-LAST:event_tbnLimpiarInformeActionPerformed

    private void btnGenerarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarInformeActionPerformed
        
        
        txtAreaInforme.setText("========= INFORME GENERAL =========\n\n");
        txtAreaInforme.append("----- PARTIDOS -----\n");
        txtAreaInforme.append(gestionPartido.listarPartidos() + "\n\n");
        txtAreaInforme.append("----- CANDIDATOS -----\n");
        txtAreaInforme.append(gestionCandidato.listarCandidatos() + "\n\n");
        txtAreaInforme.append("----- MESAS -----\n");
        txtAreaInforme.append(gestionMesas.listarMesas() + "\n\n");
        txtAreaInforme.append("----- ACTAS -----\n");
        txtAreaInforme.append(gestionActas.listarActas() + "\n\n");

    }//GEN-LAST:event_btnGenerarInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInforme().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarInforme;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloInforme;
    private javax.swing.JButton tbnLimpiarInforme;
    private javax.swing.JTextArea txtAreaInforme;
    // End of variables declaration//GEN-END:variables
}
