
package modelo.interfaces;
import modelo.entidades.MesaElectoral;
import modelo.gestion.GestionMesaElectoral;
import modelo.interfaces.FrmPrincipal;


public class FrmMesas extends javax.swing.JFrame {
    private GestionMesaElectoral gestionMesas = new GestionMesaElectoral();
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMesas.class.getName());

    /**
     * Creates new form FrmMesas
     */
    public FrmMesas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoMesa = new javax.swing.JTextField();
        txtUbicacionMesa = new javax.swing.JTextField();
        txtTotalElectores = new javax.swing.JTextField();
        btnRegistrarMesa = new javax.swing.JButton();
        btnEliminarMesa = new javax.swing.JButton();
        btnVerMesas = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestion de Mesas Electorales");

        jLabel2.setText("Codigo de Mesa");

        jLabel3.setText("Ubicacion de Mesa");

        jLabel4.setText("Total de Electores");

        txtCodigoMesa.addActionListener(this::txtCodigoMesaActionPerformed);

        btnRegistrarMesa.setText("Registrar");
        btnRegistrarMesa.addActionListener(this::btnRegistrarMesaActionPerformed);

        btnEliminarMesa.setText("Eliminar");
        btnEliminarMesa.addActionListener(this::btnEliminarMesaActionPerformed);

        btnVerMesas.setText("Ver Lista");
        btnVerMesas.addActionListener(this::btnVerMesasActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnRegistrarMesa)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoMesa)
                                .addComponent(txtUbicacionMesa)
                                .addComponent(txtTotalElectores, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminarMesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(btnVerMesas)))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUbicacionMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalElectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarMesa)
                    .addComponent(btnEliminarMesa)
                    .addComponent(btnVerMesas))
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMesaActionPerformed

    private void btnRegistrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMesaActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoMesa.getText();
    String ubicacion = txtUbicacionMesa.getText();
    int total = Integer.parseInt(txtTotalElectores.getText());

    MesaElectoral mesa = new MesaElectoral(codigo, ubicacion, total);

    boolean registrado = gestionMesas.registrarMesa(mesa);

    if (registrado) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mesa registrada.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Código repetido.");
    }
        
    }//GEN-LAST:event_btnRegistrarMesaActionPerformed

    private void btnEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMesaActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoMesa.getText();

    boolean eliminado = gestionMesas.eliminarMesa(codigo);

    if (eliminado) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mesa eliminada.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No encontrada.");
    }
    
    }//GEN-LAST:event_btnEliminarMesaActionPerformed

    private void btnVerMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMesasActionPerformed

        // TODO add your handling code here:
    String lista = gestionMesas.listarMesas();
    javax.swing.JOptionPane.showMessageDialog(this, lista);

    }//GEN-LAST:event_btnVerMesasActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        
        FrmPrincipal f = new FrmPrincipal();
    f.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMesas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarMesa;
    private javax.swing.JButton btnRegistrarMesa;
    private javax.swing.JButton btnVerMesas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCodigoMesa;
    private javax.swing.JTextField txtTotalElectores;
    private javax.swing.JTextField txtUbicacionMesa;
    // End of variables declaration//GEN-END:variables
}
